// <auto-generated />
namespace BookLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RegistrationChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RegistrationChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201801072216443_RegistrationChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
